name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install Flask

      - name: Build site
        run: |
          python web.py &
          sleep 3

      - name: Deploy
        run: |
          mkdir public
          mv templates/dashboard.html public/
          echo "<meta http-equiv=\"refresh\" content=\"0; URL='http://${GITHUB_REPOSITORY%%/*}.github.io/${GITHUB_REPOSITORY#*/}'\" />" > public/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
